
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from CRM
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from CRM
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from CRM);


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from CRM
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchase_amount) from CRM
where shipping_type in ("Standard", "Express")
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select case when subscription_status = 'Yes' then 'subscribers' else 'non-subscribers' end as status,
count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue from CRM
group by subscription_status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from CRM
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as(
select customer_id, previous_purchases,
case when previous_purchases = 1 then 'New'
	 when previous_purchases between 2 and 10 then 'Returning'
     else 'Loyal'
	End as customer_segment
from CRM)

select customer_segment, count(*) as Number_of_Customers from customer_type
group by customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
    select category, item_purchased, count(Customer_Id) as total_orders,
    ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    from CRM
    group by category, item_purchased)

select category, item_purchased, total_orders from item_counts
where item_rank <= 3;
 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from CRM
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount) AS total_revenue FROM CRM
GROUP BY age_group
ORDER BY total_revenue desc;
